### PR TITLE
feat: support `json_name` defined in a proto file

### PR DESCRIPTION
**Pull request by Yo-mah-Ya**
https://github.com/stephenh/ts-proto/issues/942

### CODE REVIEW

**Comment by stephenh** [comment]
Looks great, @Yo-mah-Ya , thanks for the PR!

Can you add-or-update one of our integration tests, to show the output is correct, and won't regress in the future?

I.e. find an existing `*.proto` file that uses `json_name`, and add `useJsonName=true` to the `parameters.txt`, call `yarn bin2ts`, and then check-in the generated/updated source. Thanks!

**Comment by stephenh** [comment]
Opps, clicked the wrong button, sorry about that!

**Comment by Yo-mah-Ya** [comment]
Hi @stephenh ,
Thanks for reviewing !
I just added integration test

**Review by stephenh — APPROVED** [review]
Looks great, thanks @Yo-mah-Ya

**Pull request merged**
