### PR TITLE
fix: problem with verbatimModuleSyntax for grpc-js

### PR DESCRIPTION
**Pull request by rosek86**
Hello, I have a few issues when verbatimModuleSyntax is enabled:

image

### CODE REVIEW

**Comment by stephenh** [comment]
hi @rosek86 , thanks for the fix! Can you run `yarn proto2ts` and push up the files that change? Having the codegen files in the PRs is basically how we do acceptance/regression testing. Thanks!

**Comment by rosek86** [comment]
done

**Review by stephenh — APPROVED** [review]

**Comment by stephenh** [comment]
Thanks @rosek86 !

**Pull request merged**
