### PR TITLE
perf: use Reader.create

### PR DESCRIPTION
**Pull request by davidzeng0**
Allows protobufjs/minimal to detect the config and optionally use BufferReader if supported.

### CODE REVIEW

**Comment by stephenh** [comment]
@davidzeng0 this looks great, but there is a failure in the build:

```
Error: illegal buffer
    at create_typed_array (/home/runner/work/ts-proto/ts-proto/node_modules/protobufjs/src/reader.js:47:15)
    at create_buffer (/home/runner/work/ts-proto/ts-proto/node_modules/protobufjs/src/reader.js:63:23)
    at Function.create_buffer_setup (/home/runner/work/ts-proto/ts-proto/node_modules/protobufjs/src/reader.js:64:15)
    at /home/runner/work/ts-proto/ts-proto/integration/simple/simple.ts:2072:78
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Disclaimer I've not looked in to it this at all, but can you tell if it's something wrong we're doing in the test, or maybe some wrinkle about `Reader.create` that we'll have to handle? Thanks!

**Comment by davidzeng0** [comment]
@stephenh It seems like the test is returning the mock value `{}` and it failing  because an object isn't a buffer. I'm not entirely sure how tests before this commit passed, but I'll look into it

**Comment by davidzeng0** [comment]
Yeah, so new Reader({}) succeeds because there are no type checkings, however Reader.create fails

image

Root cause on line 6
image

**Comment by stephenh** [comment]
@davidzeng0 Ah good find! Do you mind pushing a fix up to this PR?

**Comment by davidzeng0** [comment]
@stephenh Fixed

Also, any progress on the other 2 PRs?

Thanks.

**Pull request merged**
