### PR TITLE
fix: prefix and suffixes were not being applied to to/fromTimestamp resulting in compile error

### PR DESCRIPTION
**Pull request by halkeye**

### CODE REVIEW

**Comment by halkeye** [comment]
btw, would love if you threw a hacktoberfest label on the project or pr. Gotta get that bragging rights every year.

**Review by stephenh — APPROVED** [review]
Looks great, thanks @halkeye !

**Comment by halkeye** [comment]
I love semantic release. This is the first time I've been on the other side of it. I love it comments on pr.

Can you change the label to hacktoberfest-accepted?

**Comment by stephenh** [comment]
@halkeye yep, added the `hackoberfast-accepted` label to this and your other PR; thanks!

**Pull request merged**
