### PR TITLE
feat: support grpc-web client straming

### PR DESCRIPTION
**Pull request by luhuaei**
Use `rxjs` support client straming and server straming.

### CODE REVIEW

**Comment by stephenh** [comment]
@luhuaei thanks for the PR! I'll take a look today.

My first ask would be, can you try running `yarn proto2bin` (and not `proto2bin:local`)?

In theory this should use a docker-hosted `protoc` that should minimize any local/host-specific version of `protoc` and mean all of the `*.bin` file changes in this PR should go away.

Or if that doesn't work, let me know. Thanks!

**Comment by luhuaei** [comment]
> @luhuaei thanks for the PR! I'll take a look today.
> 
> My first ask would be, can you try running `yarn proto2bin` (and not `proto2bin:local`)?
> 
> In theory this should use a docker-hosted `protoc` that should minimize any local/host-specific version of `protoc` and mean all of the `*.bin` file changes in this PR should go away.
> 
> Or if that doesn't work, let me know. Thanks!



> @luhuaei thanks for the PR! I'll take a look today.
> 
> My first ask would be, can you try running `yarn proto2bin` (and not `proto2bin:local`)?
> 
> In theory this should use a docker-hosted `protoc` that should minimize any local/host-specific version of `protoc` and mean all of the `*.bin` file changes in this PR should go away.
> 
> Or if that doesn't work, let me know. Thanks!

Oh, I donot known `yarn run build:test` will only effect `grpc-web` relative example `.bin` files.  Thanks for mentiion

Already change https://github.com/stephenh/ts-proto/pull/617/commits/5fa68dccd20be42db7a6f9c55d5f2a7997c44d63

**Review by stephenh — APPROVED** [review]
This looks great @luhuaei , thank you!

**Comment by stephenh** [comment]
@luhuaei looks like there is a small conflict against `main` b/c we just had another PR land that allows customizing the retry behavior; once that is resolved, I'll merge this in, thanks!

**Comment by luhuaei** [comment]
> @luhuaei looks like there is a small conflict against `main` b/c we just had another PR land that allows customizing the retry behavior; once that is resolved, I'll merge this in, thanks!

Thank you! @stephenh

**Comment by stephenh** [comment]
Just hit merge, and it will auto-release soon; thanks @luhuaei !

**Pull request merged**
