### PR TITLE
style: fix style and remove unnecessary code

### PR DESCRIPTION
**Pull request by davidzeng0**
Should be merged after the other 3 PRs
Going to need a rebase before merging for an integration test

### CODE REVIEW

**Comment by davidzeng0** [comment]
Rebased, should allow for automatic merging

**Review by stephenh — APPROVED** [review]
Thanks for these fixups! Feel free to rebase and merge whenever you want.

In general, your contributions have been great, and I really appreciate them. If you feel confident about any future PRs, feel free to start approving and releasing them w/o waiting for me, if I get too far behind.

Basically I'd appreciate your help as a collaborator/maintainer of the project, if you're interested. Thanks!

**Comment by davidzeng0** [comment]
> In general, your contributions have been great, and I really appreciate them. If you feel confident about any future PRs, feel free to start approving and releasing them w/o waiting for me, if I get too far behind.

> Basically I'd appreciate your help as a collaborator/maintainer of the project, if you're interested. Thanks!

Will do :)

**Pull request merged**
