### PR TITLE
feat: omit optional fields in base instance

### PR DESCRIPTION
**Pull request by robot9706**
Releated to #494 and #492.
Should fix the issue where nextjs is unable to serialize server side props.

By default the feature is disabled so nothing changes in the genererated code, optional fields can be omited using the "omitOptionalUndefineds=true" option.

### CODE REVIEW

**Comment by stephenh** [comment]
Hey @robot9706 , thanks for the PR!

I'm remembering this issue now... I think this sounds good, to fix it via a flag. A few asks:

* And you run `yarn proto2bin` in the top-level directory? This should use docker to generate the `*.bin` files and so be host & protoc-version independent. Basically they shouldn't show up as changed in your PR.

* Can you add a new `integration-tests/*` directory with a super-small `*.proto` and `parameters.txt` that shows the generated output with the new flag enabled?

* Maybe call this `initializeFieldsAsUndefined=true/false`? Wdyt of that name?

* Should we change `initializeFieldsAsUndefined` to `false` if `nestJs=true` is set?

* Can you add a note about the new flag to the readme?

Apologies for the ~3-4 asks, but overall this lgtm and we can work on getting it merged. Thanks!

**Comment by robot9706** [comment]
Hi! Thanks for checking out the PR!

> * And you run `yarn proto2bin` in the top-level directory? This should use docker to generate the `*.bin` files and so be host & protoc-version independent. Basically they shouldn't show up as changed in your PR.

I did run `yarn proto2bin` in the top-level directory, I'll look into fixing the test files then.

> * Can you add a new `integration-tests/*` directory with a super-small `*.proto` and `parameters.txt` that shows the generated output with the new flag enabled?

Yes, sure.

> * Maybe call this `initializeFieldsAsUndefined=true/false`? Wdyt of that name?

In my opinion this option should be disabled by default since it changes some optimisations, that's why I wanted to name it something which reflects that it's off by default, and setting to "true" enables it.
But `initializeFieldsAsUndefined` works for me as well if you think that's a better name. 

> * Should we change `initializeFieldsAsUndefined` to `false` if `nestJs=true` is set?

That's a good question, I think it yes that could be the default behaviour but I'll think about it and get back to you.

> * Can you add a note about the new flag to the readme?

Oh I forgot to add the new flag to the readme, my bad.

**Comment by robot9706** [comment]
I pushed some changes:

- Changed the name of the option to the one you suggested, also made sure to set it to `false` if `nextJs` is enabled.
- Added a new integration test.

After rebuilding the tests loads of other `*.bin` files changes as well, I'm not sure if I should commit these files... any input on these?

**Comment by stephenh** [comment]
Hey @robot9706 , this looks great! The CI build failed with a very minor failure I fixed by just merging main in #669 , and so your work got merged via that PR and I'll close this one out. Thanks!

**Comment by robot9706** [comment]
Thanks for your help!

**Pull request closed without merging**
