### PR TITLE
perf: Faster base64FromBytes & bytesFromBase64 on Node.JS

### PR DESCRIPTION
**Pull request by coyotte508**
I didn't change the browser code but `for .. of` would probably be more performant than `forEach` on it

### CODE REVIEW

**Comment by stephenh** [comment]
@coyotte508 looks great! Looks like there are a few test failures/need the `fix` / `feat` prefix for your PR, but otherwise lgtm. Thanks!

**Comment by coyotte508** [comment]
The failing test was caused because expecting a Uint8Array instead of a Buffer (even though Buffer is a subclass of Uint8Array and is type-compatible since node 4.x).

I used `Uint8Array.from()` to convert the buffer back to an `Uint8Array`

**Comment by stephenh** [comment]
Thanks @coyotte508 , I'll hit merge!

**Pull request merged**
