### PR TITLE
feat: add meta-data to stream error

### PR DESCRIPTION
**Pull request by hersentino**
This PR introduces metadata support in Stream (invoke) during catch as in Unary. It's required to read gRPC richer errors.
S

### CODE REVIEW

**Comment by stephenh** [comment]
@hersentino cool, this looks good to me; can you run `yarn bin2ts` to update the generated code in `integration/`? Having the code output checked basically acts as our regression suite. Thanks!

**Comment by hersentino** [comment]
@stephenh If you check pr changes we can see `integration/grpc-web/example.ts` has been updated. To be sur I ran `yarn bin2ts` again and nothing change

**Comment by stephenh** [comment]
@hersentino ah! yep, I see it that now, sorry I was just expecting more files than just this one to change, but I guess this is the only integration test we have for this output right now. Which is fine, I'll merge. Thanks!

**Comment by hersentino** [comment]
Ok perfect ! Thank you

**Pull request merged**
