### PR TITLE
fix: typescript errors for struct with optional=all

### LINKED ISSUE #578: Compile Error with structs and useOptionals=all
Version 1.114.7
`useOptionals=all`

Doesn't seem to be properly handling struct fields.  Either the generated struct code needs to add `?` unwrapping logic or it should remove the optionality on the `fields` / `values` properties.

```zsh
protoc --proto_path=./src/proto --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=./src/proto/generated/ $(find ./src/proto/models -iname "*.proto") --ts_proto_opt=useOptionals=all --ts_proto_opt=outputPartialMethods=false --ts_proto_opt=unrecognizedEnum=false --ts_proto_opt=stringEnums=true --ts_proto_opt=useDate=false --ts_proto_opt=oneof=unions --ts_proto_opt=outputJsonMethods=false --ts_proto_opt=fileSuffix=.pb
        
[10:49:33] Finished 'protoc' after 1.25 s
[10:49:35] Starting 'dev'...
[10:49:35] Starting 'typescript'...
[10:49:35] src/proto/generated/google/protobuf/struct.pb.ts:134:9 - error TS2532: Object is possibly 'undefined'.

134         struct.fields[key] = object[key];
            ~~~~~~~~~~~~~

[10:49:35] src/proto/generated/google/protobuf/struct.pb.ts:142:17 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(o: {}): string[]', gave the following error.
    Argument of type '{ [key: string]: any; } | undefined' is not assignable to parameter of type '{}'.
      Type 'undefined' is not assignable to type '{}'.
  Overload 2 of 2, '(o: object): string[]', gave the following error.
    Argument of type '{ [key: string]: any; } | undefined' is not assignable to parameter of type 'object'.
      Type 'undefined' is not assignable to type 'object'.

142     Object.keys(message.fields).forEach((key) => {
                    ~~~~~~~~~~~~~~


[10:49:35] src/proto/generated/google/protobuf/struct.pb.ts:143:21 - error TS2532: Object is possibly 'undefined'.

143       object[key] = message.fields[key];
                        ~~~~~~~~~~~~~~

[10:49:35] src/proto/generated/google/protobuf/struct.pb.ts:358:5 - error TS2322: Type 'any[] | undefined' is not assignable to type 'any[]'.
  Type 'undefined' is not assignable to type 'any[]'.

358     return message.values;
        ~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by UnderKoen**
Fixes #578 

Due to the use of the `.foreach` function TS has no context of the clue that `struct.fields` is definently not undefined.

### CODE REVIEW

**Comment by stephenh** [comment]
Hi @UnderKoen , thanks for the PR! Can you run `yarn bin2ts` in your local copy, and check those into the commit/PR?

Given that ts-proto's primary output is generated code, we go ahead and commit the generated code to the repo because it forms ts-protos regression suite.

Thanks!

**Comment by UnderKoen** [comment]
@stephenh Thanks for the information. I have pushed that in the pr!

**Comment by stephenh** [comment]
@UnderKoen sorry, looks like just a formatting thing, if you don't mind fixing that? :pray: Thanks!

**Comment by UnderKoen** [comment]
@stephenh Done!

**Comment by stephenh** [comment]
Looks great, thanks @UnderKoen !

**Pull request merged**
