### PR TITLE
chore: publish new ts-proto-descriptors

### PR DESCRIPTION
**Pull request by davidzeng0**
ts-proto: ts-proto-descriptors version bump
build.sh: output extensions
ts-proto-descriptors: bump ts-proto version and minor version bump

### CODE REVIEW

**Comment by davidzeng0** [comment]
I'm not familiar with publishing but this commit may help
(build failing because new package version is not published yet)

**Comment by stephenh** [comment]
Ah yeah, sorry, I don't have publishing of `ts-proto-descriptors` automated.

I just checked this out locally and ran `yarn npm publish` in the `protos/` directory, so `ts-proto-descriptors` 1.9.0 should be released now.

**Comment by davidzeng0** [comment]
Thanks

**Pull request merged**
