### PR TITLE
refactor: export createBaseMessage function

### PR DESCRIPTION
**Pull request by paralin**
It's useful to be able to construct a message:

const message = createBaseMessage()

### CODE REVIEW

**Comment by paralin** [comment]
I guess it's possible to do MessageType.fromPartial({}) as well. Up to you if you'd like to merge this @stephenh

**Comment by paralin** [comment]
Meh, I'm OK with fromPartial({}).

**Comment by stephenh** [comment]
Cool, yeah, I'm good with sticking with `fromPartial`.

Fwiw one of the "ts-proto 2.x" ideas is to remain `fromPartial` to something "less solution-oriented" (i.e. that it accepts partial types), to be something like just `MessageType.from` or `MessageType.create`.

**Comment by paralin** [comment]
@stephenh I think it might make sense to add MessageType.create today, accepting an optional parameter which, if set, is passed to fromPartial.

```
  create<I extends Exact<DeepPartial<MyMessage>, I>>(obj?: I): MyMessage {
    return MyMessage.fromPartial(obj || {})
  }
```

Thoughts?

**Comment by stephenh** [comment]
@paralin yep, sgtm

**Comment by paralin** [comment]
@stephenh submitted here: https://github.com/stephenh/ts-proto/pull/760

**Pull request closed without merging**
