### PR TITLE
feat: add dynamic upStreamCodes option

### PR DESCRIPTION
**Pull request by hersentino**
This PR introduces dynamic upStreamCodes option following discussions on #539

### CODE REVIEW

**Review by doctorpangloss — CHANGES_REQUESTED** [review]
The default upstream codes should be an empty array, it never makes sense for this code to retry. Let the application always decide what to do by default

**Comment by hersentino** [comment]
@stephenh all done :)

**Comment by stephenh** [comment]
Thanks @hersentino !

**Pull request merged**
