### PR TITLE
feat: Add options to limit generation of encode and decode methods to only specific message types

### PR DESCRIPTION
**Pull request by akrennmair**
I created this PR as a possible to solution to the feature request submitted in #1084.

I added integration tests for test coverage, and updated the documentation to include the two new options.

### CODE REVIEW

**Comment by stephenh** [comment]
Hi @akrennmair , thanks for updating the PR! Looks like there is a build error with `MessageFns`...maybe we need two/separate input/output `MessageFns` types?

**Comment by akrennmair** [comment]
@stephenh I didn't want to touch the `MessageFns` type as I didn't know what it would break. What I did instead was to generate a tiny dummy encode or decode method that throws an error if the presence of the method is required.

**Comment by stephenh** [comment]
Sounds great, thanks @akrennmair !

**Pull request merged**
