### PR TITLE
feat: adds support for emitting default scalar values in json

### PR DESCRIPTION
**Pull request by wgottschalk**
Adds a new option for emitting default fields to support https://github.com/stephenh/ts-proto/issues/907

Note that I only added support for the `toJSON` method. I designed the option to be easily modified to accept an array of fields similar to `snakeToCamel`. I didn't support the encoders or extensions because I'm not sure how to properly test those methods. If there's any code samples, I'd be happy to take a look and implement that

### CODE REVIEW

**Comment by stephenh** [comment]
Hey @wgottschalk ! Thanks for the PR! Apologies for the delay reviewing, have just been busy...

Fwiw I'm kind of dumb-founded that this so-obvious-in-retrospect slice point for "output default or not" already existed...it's been so long since I was deep in this code, but :shrug: , that's why we have smart & motivated contributors like yourself I guess! :tada: 

Looks like maybe there is a small options test failing, just b/c of the new option you added, I assume.

Also do you mind running format/prettier on `integration/emit-default-values-json/emit-default-values-test.ts`?

Otherwise it looks great, and I'll merge once the build is passing!

**Comment by stephenh** [comment]
> I didn't support the encoders or extensions because I'm not sure
> how to properly test those methods.

I think the encoders are probably fine to leave as-is, b/c they output a binary format that a) no one sees, and b) b/c it's binary most implementations pretty strictly follow it, vs. the JSON encoding where it's got this "someone people want defaults/some don't" nuance. 

By extensions, what are you referring to? Sorry, just not following/remembering.

**Comment by wgottschalk** [comment]
> Looks like maybe there is a small options test failing, just b/c of the new option you added, I assume.
> Also do you mind running format/prettier on integration/emit-default-values-json/emit-default-values-test.ts?

Just updated the snapshots and ran formatting on the directory.

**Comment by wgottschalk** [comment]
> By extensions, what are you referring to? Sorry, just not following/remembering.

There's a function called generateExtension which has a call to notDefaultChecked

https://github.com/stephenh/ts-proto/blob/df0c59631d5dcb4f7c0413ac57d2045a7726b1f5/src/main.ts#L1519

https://github.com/stephenh/ts-proto/blob/df0c59631d5dcb4f7c0413ac57d2045a7726b1f5/src/main.ts#L1617-L1624

**Comment by stephenh** [comment]
Looks great @wgottschalk , thanks!

**Pull request merged**
