### PR TITLE
feat: output-encode-only methods

### PR DESCRIPTION
**Pull request by Frabat**
As requested by me in https://github.com/stephenh/ts-proto/issues/773, I've changed the outputEncodeMethods to accept also "encode-only" and "decode-only" string values.
Since my use case also didn't need the creation methods, I've added a third option "encode-no-creation" that doesn't export that. 
In theory, this could be included with the "encode-only" flag, since the creation method is used just by the encoder, but somebody might need it.

### CODE REVIEW

**Review by stephenh — APPROVED** [review]
@Frabat looks like the build failed with a prettier error, but otherwise looks good to me! Thanks!

**Comment by Frabat** [comment]
Hi @stephenh can I solve the prettier error or is something CI related?

**Comment by stephenh** [comment]
@Frabat if you run `yarn format` in the root directory, it should resolve the prettier errors, and then just push those changes up to the PR.

**Comment by Frabat** [comment]
@stephenh done!

**Comment by stephenh** [comment]
Erg, sorry for the flakey tests, I think we had several tests sharing the same port. I believe I've fixed it in:

https://github.com/stephenh/ts-proto/pull/790

Can you rebase on top of that / on top of main? Thank you!

**Comment by stephenh** [comment]
Looks great! Thanks @Frabat !

**Pull request merged**
