### PR TITLE
feat: add option to use async iterables

### PR DESCRIPTION
**Pull request by paralin**
Adds option `useAsyncIterable` which uses `AsyncIterable` instead of `Observable`.

For example:

```ts
  bidirectionalStreamingRequest(
    service: string,
    method: string,
    data: AsyncIterable<Uint8Array>
  ): AsyncIterable<Uint8Array>
```

Generates `Transform` async iterables for encoding and decoding:

```ts
  // encodeTransform encodes a source of message objects.
  // Transform<TestMessage, Uint8Array>
  async *encodeTransform(
    source: AsyncIterable<TestMessage | TestMessage[]> | Iterable<TestMessage | TestMessage[]>
  ): AsyncIterable<Uint8Array> {
    for await (const pkt of source) {
      if (Array.isArray(pkt)) {
        for (const p of pkt) {
          yield* [TestMessage.encode(p).finish()];
        }
      } else {
        yield* [TestMessage.encode(pkt).finish()];
      }
    }
  },
```

```ts
  // decodeTransform decodes a source of encoded messages.
  // Transform<Uint8Array, TestMessage>
  async *decodeTransform(
    source: AsyncIterable<Uint8Array | Uint8Array[]> | Iterable<Uint8Array | Uint8Array[]>
  ): AsyncIterable<TestMessage> {
    for await (const pkt of source) {
      if (Array.isArray(pkt)) {
        for (const p of pkt) {
          yield* [TestMessage.decode(p)];
        }
      } else {
        yield* [TestMessage.decode(pkt)];
      }
    }
  },
```

Generates RPC service implementations which use the Transform iterators:

```ts
  BidiStreaming(request: AsyncIterable<TestMessage>): AsyncIterable<TestMessage> {
    const data = TestMessage.encodeTransform(request);
    const result = this.rpc.bidirectionalStreamingRequest('simple.Test', 'BidiStreaming', data);
    return TestMessage.decodeTransform(result);
  }
```

`AsyncIterable`s indicate a stream has ended by closing with an optional error.

### CODE REVIEW

**Comment by paralin** [comment]
Note: I avoided using `it-stream-types` to avoid the extra dependency:

```
export type Source<T> = AsyncIterable<T> | Iterable<T>
source: Source<Uint8Array | Uint8Array[]>
```

=>

```
source: AsyncIterable<Uint8Array | Uint8Array[]> | Iterable<Uint8Array | Uint8Array[]>
```

**Comment by paralin** [comment]
Migrated to using `AsyncIterable` only: https://github.com/aperturerobotics/starpc/commit/396430398854bcd4222796f2ac0098532698de56

**Comment by paralin** [comment]
@stephenh Tested this & released for starpc, converted everything to AsyncIterable from Observable: https://github.com/aperturerobotics/starpc/commit/4ecfbe987f4b44ccfeec050b363f16d6c3e1d803

**Comment by paralin** [comment]
@stephenh This is ready to go now that #603 is merged

**Comment by stephenh** [comment]
Looks great, thanks!

**Comment by paralin** [comment]
Awesome, thanks @stephenh !

**Pull request merged**
