### PR TITLE
constEnums option

### PR DESCRIPTION
**Pull request by lxgreen**
This PR adds an integration test case for `const enum` generation option (#230)

### CODE REVIEW

**Comment by stephenh** [comment]
Looks great! I realize in retrospect my comment was ambiguous, but could you go ahead and take a crack at changing `main.ts` to output the enum with the `const` keyword?

It'll be somewhere around here:

https://github.com/stephenh/ts-proto/blob/master/src/enums.ts#L22

And then `options.ts` for adding the new `constEnums` option.

**Comment by lxgreen** [comment]
sure! you just had to tell me, just fix it! 😄

**Comment by lxgreen** [comment]
full solution in #232

**Comment by stephenh** [comment]
Looked great, thanks!

**Pull request closed without merging**
