### PR TITLE
feat: option fromPartialDefaultInitialize=false

### PR DESCRIPTION
**Pull request by davidzeng0**
Should be merged after https://github.com/stephenh/ts-proto/pull/806

### CODE REVIEW

**Comment by stephenh** [comment]
@davidzeng0 wdyt about instead of adding a new option, we just use `initializeFieldsAsUndefined` and assume that if the user has set `initializeFieldsAsUndefined=false` then they also want `fromPartial` to leave fields uninitialized? 

Would that work, or am I missing something?

**Comment by stephenh** [comment]
Also, just in general thanks for all the PRs! I don't always have time to respond to them during the week, but will try to catch up with you on the weekends. :-) 

(...also do you mind rebasing your PRs as each prior one is merged? For some reason GitHub doesn't update the diffs/list of commits to exclude your prior work; would be great if it just did that automatically imo.)

Thanks!

**Comment by davidzeng0** [comment]
Yes, I don't mind rebasing. I will be PRing as long as I come across missing features that I need to use :).

I only added a new option because I thought that "initializeFieldsAsUndefined" is a decoding option, and it might make sense for an encoding option, but they can be the same option. Something else I can also fix is https://github.com/stephenh/ts-proto/issues/682

**Comment by davidzeng0** [comment]
https://github.com/davidzeng0/ts-proto/commit/fa2d5df25c37d2acb5370c0f2b3b06bfd2a5719f uses the existing option
https://github.com/davidzeng0/ts-proto/commit/b5481ceb77f527e2d55725e4a685000b29c238c5 removes default initialization fir json

**Pull request closed without merging**
