### PR TITLE
fix: initialize undefined optional fields upon use

### PR DESCRIPTION
**Pull request by davidzeng0**

### CODE REVIEW

**Comment by stephenh** [comment]
@davidzeng0 I've merged your other two PRs, so this one has a conflict now; could you rebase it? Thanks!

**Comment by davidzeng0** [comment]
Rebased

**Comment by stephenh** [comment]
@davidzeng0 Ah great, thanks for rebasing; can you try and find an existing `integration/*` test that matches the `parameters.txt` you're using and add a reproduction of what would previously blow up, but now does not?

Just to keep this behavior from regressing.

Also, do you think this PR will fix this issue:

https://github.com/stephenh/ts-proto/issues/788

My guess is yes?

Thanks!

**Comment by davidzeng0** [comment]
This should fix https://github.com/stephenh/ts-proto/issues/788 and https://github.com/stephenh/ts-proto/issues/736

**Comment by davidzeng0** [comment]
As expected, the test fails without https://github.com/stephenh/ts-proto/pull/802/commits/6f6f97d78d0322f9d43b8e56e4dcfe00af855ad3

**Comment by stephenh** [comment]
Great integration test, thank you!

**Pull request merged**
