### PR TITLE
Adds the option `configureProtobuf` for issue #78

### PR DESCRIPTION
**Pull request by timostamm**
This PR adds a new option flag `configureProtobuf`. 

When `true`, the following code will be appended to each generated file:
```typescript
if (protobuf.util.Long !== Long) {
  protobuf.util.Long = Long;
  protobuf.configure();
}
```

With the following imports (added with `ts-poet`): 
```typescript
import * as protobuf from 'protobufjs/minimal';
import * as Long from 'long';
```

No test coverage. Maybe a use case for #111 ?

### CODE REVIEW

**Comment by stephenh** [comment]
@timostamm hey, I think this generally makes sense, although I'm wondering if we should just always do it, i.e. if `forceLong=long` is on? I suppose being able to turn it _off_ makes sense (i.e. maybe we should keep the config value), but defaulting on seems like a good idea?

**Comment by stephenh** [comment]
I'd also like to do this only once somehow, instead of once-per-generated file. Like have some sort of `global.tsProtoHasInitialized` or something like that, that we first check. Seems like that'd be a good idea? Maybe not a huge deal if the `.configure` call is cheap I guess, so might be prematurely optimizing...wdyt?

**Comment by timostamm** [comment]
Hey @stephenh , 

Only emitting the snippet when `forceLong=long` would not work. The `configure()` is also necessary for `forceLong=string` because `Long.js` is required to convert from [LongBits](https://github.com/protobufjs/protobuf.js/blob/master/src/util/longbits.js) to `string`. 

`protobuf.configure()` will run only once. The if statement above makes sure of that. 

Inverting the option `configureProtobuf` should work fine. Is `dontConfigureProtobuf` a fitting name?

**Comment by stephenh** [comment]
> protobuf.configure() will run only once

Ah right, right, sorry I missed that.

> Is dontConfigureProtobuf a fitting name

I like `configureProtobuf` as the name, I'm just thinking it should default to `true` if `forceLong` is set to `string` or `long`? I.e. it's only if `forceLong=number` that we could skip this? Is that right?

**Comment by timostamm** [comment]
@stephenh, thanks for your feedback and sorry for my late response. 
I have updated the PR accordingly. 

I have noticed that PR #125 overlaps with this PR. Please feel free to accept or drop my PR as you see fit. No bad feelings at all if you decide PR #125 is the better way to go.

**Comment by stephenh** [comment]
Fixed through #125; thanks @timostamm and sorry again for not realizing the overlap sooner!

**Pull request closed without merging**
