### PR TITLE
Several feature additions and fixes

### PR DESCRIPTION
**Pull request by davidzeng0**
1. Adds group encoding and decoding support
2. Uses Reader.create for faster decoding
3. Generate _unknownFields for generic service options (extensions are planned)
4. useOptionals=all, initializeFieldsAsUndefined=false, initialize maps and repeated fields on use

### CODE REVIEW

**Comment by davidzeng0** [comment]
Since the rest of the repo is not updated for ts-proto 6.4.1, neither are the commits in this pull request

**Comment by stephenh** [comment]
Hi @davidzeng0 ; thanks for the PR!

Do you mind breaking each of your changes out as a separate PR? Fwiw it looks like your commits are already very clean, so hopefully that would be too bad?

Of your changes:

1. Adds group encoding and decoding support
2. Uses Reader.create for faster decoding
3. Generate _unknownFields for generic service options (extensions are planned)
4. useOptionals=all, initializeFieldsAsUndefined=false, initialize maps and repeated fields on use

I think 2-4 all sound great and would be obvious PRs to land.

I'm a little hesitant about 1, b/c a) afaict groups are basically deprecated, and b) just scanning the PR I'm kinda surprised more work was not necessary to make them work; could you add an integration test that shows groups encoding/decoding working as expected?

I'm still on the fence about supporting groups, but if the code changes are minimal, and we have an integration test showing that it does actually work, then I'd be fine accepting it.

Thanks!

**Comment by davidzeng0** [comment]
Sure thing

I added group support because I'm using some very old .proto files that uses groups and I've already thoroughly tested that they do in fact work (I basically copied the generating format from protoc's C++ code, then tested on --decode_raw)

**Comment by davidzeng0** [comment]
Going to create separate pull requests

**Pull request closed without merging**
